# Generated by Django 3.0.4 on 2020-04-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Found',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('uid', models.IntegerField()),
                ('card', models.CharField(choices=[('adhar', 'Adhar Card'), ('voterid', 'Voter Id Card'), ('passport', 'Passport'), ('atm', 'Atm Card')], default='Adhar Card', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Lost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('uid', models.IntegerField()),
                ('card', models.CharField(choices=[('adhar', 'Adhar Card'), ('voterid', 'Voter Id Card'), ('passport', 'Passport'), ('atm', 'Atm Card')], default='Adhar Card', max_length=50)),
            ],
        ),
    ]
