# Generated by Django 3.0.4 on 2020-04-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_auto_20200417_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='found',
            name='cardholder_name',
            field=models.CharField(default='deepa', max_length=150),
            preserve_default=False,
        ),
    ]
