# Generated by Django 3.0.4 on 2020-04-19 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_found_cardholder_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='found',
            name='email',
            field=models.EmailField(default='deepa@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lost',
            name='email',
            field=models.EmailField(default='NULL', max_length=254),
            preserve_default=False,
        ),
    ]
